### PR TITLE
Update fullData.json

### PR DESCRIPTION
**Pull request by PopiJack**
Zdá sa mi, že aj tu je chyba.
Zdroj: https://penpoin.com/what-is-gross-investment/ Gross investment is the sum of expenditures for new capital purchases and the replacement of depreciated capital. The company buys new capital goods, such as factories and equipment, to increase its production capacity. Meanwhile, capital replacement is to maintain existing capacity.

### CODE REVIEW

**Comment by benkosa** [comment]
suhlasim :)

**Comment by benkosa** [comment]
nebude aj toto zle? 
image

**Comment by PopiJack** [comment]
No, nie som si celkom isty. Teraz pozeram na tej istej stránke a keď sa odpisy = dph tak potom to je správne.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by PopiJack** [comment]
No ako môže to byť aj tá tretia možnosť : https://encyklopediapoznania.sk/clanok/1680/hrube-investicie
Ale je to divný zdroj xd

Ale aj tu pri tejto otázke som sa pozastavil a ako nie je to normalny zdroj, ale toto mi vyhodilo ChatGPT : 
The demand for land is affected by the quality of the land in several ways. High-quality land, such as land with fertile soil or land that is well-suited for commercial or residential development, will typically have a higher demand than lower-quality land. Additionally, land that is located in desirable areas, such as near urban centers or popular tourist destinations, will also have a higher demand. Conversely, land that is located in remote or less desirable areas, or land that is contaminated or otherwise difficult to use, will have a lower demand.



Screenshot 2023-01-15 at 18 52 11

**Comment by benkosa** [comment]
zevraj to je spravne tak ako to je

**Pull request merged**
